Traceback (most recent call last):
  File "/home/theo/.local/share/hatch/env/virtual/hylight/pWfKuxou/hylight/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/theo/.local/share/hatch/env/virtual/hylight/pWfKuxou/hylight/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theo/.local/share/hatch/env/virtual/hylight/pWfKuxou/hylight/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/theo/.local/share/hatch/env/virtual/hylight/pWfKuxou/hylight/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/theo/.local/share/hatch/env/virtual/hylight/pWfKuxou/hylight/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/theo/.local/share/hatch/env/virtual/hylight/pWfKuxou/hylight/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from hylight.guess_width import guess_width, OmegaEff, ExPES

width = guess_width(outcar, (poscar_gs, poscar_es), fc_shift_gs, fc_shift_es, T, omega_eff_type=OmegaEff.FC_MEAN, ex_pes=ExPES.ISO_SCALE)
print(f"Guessed line FWHM = {width*1e3:0.1f} meV")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mhylight[39;00m[38;5;21;01m.[39;00m[38;5;21;01mguess_width[39;00m [38;5;28;01mimport[39;00m guess_width, OmegaEff, ExPES
[1;32m      3[0m width [38;5;241m=[39m guess_width(outcar, (poscar_gs, poscar_es), fc_shift_gs, fc_shift_es, T, omega_eff_type[38;5;241m=[39mOmegaEff[38;5;241m.[39mFC_MEAN, ex_pes[38;5;241m=[39mExPES[38;5;241m.[39mISO_SCALE)
[1;32m      4[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mGuessed line FWHM = [39m[38;5;132;01m{[39;00mwidth[38;5;241m*[39m[38;5;241m1e3[39m[38;5;132;01m:[39;00m[38;5;124m0.1f[39m[38;5;132;01m}[39;00m[38;5;124m meV[39m[38;5;124m"[39m)

[0;31mImportError[0m: cannot import name 'ExPES' from 'hylight.guess_width' (/home/theo/.local/share/hatch/env/virtual/hylight/pWfKuxou/hylight/lib/python3.11/site-packages/hylight/guess_width.py)

